<?php

return array(

	/*
	|--------------------------------------------------------------------------
	| Setup language lines
	|--------------------------------------------------------------------------
	|
	| This file defines language lines used by the setup pages
	|
	*/

	"installer"         => "Sticky Notes Installer",
	"welcome"           => "Thank you for choosing Sticky Notes. The installer will guide you throughout ".
	                       "the install process. Follow the simple steps for a hassle free installation!",
	"develop_warn"      => "<b>Important:</b> You are attempting to set up a pre-release version. It is ".
	                       "strongly recommended that you do not install development versions on production ".
	                       "servers. To download the latest stable release instead, <a href='%s'>click here</a>.",
	"i_stage1_title"    => "Stage 1: Database configuration",
	"i_stage1_exp"      => "Open your database configuration file located at <code>app/config/database.php</code> ".
	                       "and fill up your DB details. Sticky Notes uses one active connection only, so make ".
	                       "sure you change the 'default' database driver accordingly. See <a href='http://codebright".
	                       ".daylerees.com/database'>this guide</a> for more information on DB configuration.",
	"i_stage2_title"    => "Stage 2: Ready to install",
	"i_stage2_exp"      => "Your database settings look good. Whenever you are ready, click on the <code>Start ".
	                       "installation</code> button to begin the automated installed process.",
	"i_stage3_title"    => "Stage 3: Installation in progress",
	"i_stage3_exp"      => "Sticky Notes is being installed on your server. This may take several minutes...",
	"i_stage4_title"    => "Stage 4: Complete installation",
	"i_stage4_exp"      => "Sticky Notes has been successfully installed! Please make a note of the following ".
	                       "credentials for logging into the admin panel.",
	"u_stage1_title"    => "Stage 1: Select update version",
	"u_stage1_exp"      => "The update utility upgrades your database tables with the latest data. You must be ".
	                       "running one of the following versions of Sticky Notes previously in order to use this ".
	                       "tool. Please make sure that you select the correct version below.",
	"u_stage2_title"    => "Stage 2: Update in progress",
	"u_stage2_exp"      => "Sticky Notes is being updated. This may take several minutes...",
	"u_stage3_title"    => "Stage 3: Update complete",
	"u_stage3_exp"      => "Sticky Notes has been successfully updated! You can now start using your new version.",
	"proceed_login"     => "Proceed to login &rarr;",
	"click_check"       => "Once you have filled in the correct DB details, click on the <code>Test connection</code> ".
	                       "button.",
	"update_config"     => "If you wish to have your old site configuration (settings) migrated into the new Sticky Notes, ".
	                       "please place your old <code>config.php</code> inside <code>app/config</code> folder.",
	"test_connection"   => "Test connection",
	"test_fail"         => "Database connection failed with the following error: %s",
	"install_warn"      => "<b>Important</b>: The installer will drop all Sticky Notes tables. If you are upgrading from ".
	                       "an older version, use the %s instead.",
	"update_util"       => "update utility",
	"start_install"     => "Start installation",
	"initializing"      => "Initializing...",
	"create_table"      => "Creating table: %s",
	"create_index"      => "Creating indexes...",
	"almost_done"       => "Almost done...",
	"install_complete"  => "Installation complete.",
	"update_complete"   => "Update complete.",
	"complete"          => "complete",
	"error_occurred"    => "An error occurred",
	"error_title"       => "Setup failed",
	"error_exp"         => "An error occurred and setup has been aborted. The error message has been displayed below:",
	"process_version"   => "Installing new changes after version %s...",
	"update_from"       => "Update from",
	"start_update"      => "Start update",
	"return_sn"         => "Return to Sticky Notes &rarr;",
	"ldap_update_warn"  => "It appears that you have been using LDAP authentication before. Newer versions of Sticky Notes ".
	                       "support logins for both users and admins in contrast to admin-only logins in older versions. ".
	                       "In view of that, a new parameter <code>admin filters</code> has been added to your LDAP ".
	                       "configuration options which you will need to set in the admin panel. Without that option, all ".
	                       "users that log in will get admin privileges.",
	"update_notifs"     => "Notifications",
	"update_notifs_exp" => "These are the notification messages generated by individual updaters that you have run as a part ".
	                       "of the update process. These messages can contain important security warning, so it is strongly ".
	                       "recommended that you read them and take the suggested measures.",
	"notify_version"    => "Version %s updater",

);
